### ISSUE TITLE
Hiding isn't working

### ISSUE THREAD

**Issue by mark-bradshaw** [terebentina/react-popover#10]
I just noticed that hiding isn't working in v1.2.0.  I believe I've traced the issue to 

``` js
hide = () => {
    if (!this.immune) {
        this.setState({ isPopoverShown: false });
    }
```

When it comes to hiding, the `this.immune` value is `true`, so that setState never fires.  I'm not sure if `this.immune` is needed any more after the last code change.  It seems that just having a single callback in the popover store effectively takes care of the same need, but I could be wrong.  If you take out `this.immune` it seems that the code gets more straightforward.

**Comment by terebentina** [comment]
Oh, right, `immune` isn't needed anymore. Got to write those tests! :)

**Comment by mark-bradshaw** [comment]
They're a pain, but they help. :)
