### ISSUE TITLE
PopoverWrapper closes when I click on an item in the Popover

### ISSUE THREAD

**Issue by stahlmanDesign** [terebentina/react-popover#13]
I got the PopoverWrapper working so that it closes when I click outside the Popover, but I want the Popover to stay open while I click on items in the popover. Is there an easy way to detect that I'm in the popover, and prevent it from closing on click?

**Comment by terebentina** [comment]
Try adding `e.stopPropagation();` to the click handler for the items inside the popover (where `e` is the event)

**Comment by stahlmanDesign** [comment]
Thanks, works perfectly.
