### ISSUE TITLE
Example not working:

### ISSUE THREAD

**Issue by msimonc** [terebentina/react-popover#2]
Warning: Failed propType: Invalid prop `trigger` supplied to `Popover`, expected a single ReactElement. Check the render method of ...

import Popover from '@terebentina/react-popover';

import '@terebentina/react-popover/lib/styles.css';

export default class NetworkStatPage extends React.Component {

```
render() {
    return (
        <div>
            If you want to see a nice popover
            <Popover position="bottom" className="awesome" trigger="click me">
                here I am in all my glory!
            </Popover>
        </div>
    );
}
```

}

**Comment by terebentina** [comment]
This is strange...which version of React?

**Comment by terebentina** [comment]
fixed, sorry for that.
