### ISSUE TITLE
Inline styles

### ISSUE THREAD

**Issue by mark-bradshaw** [terebentina/react-popover#5]
Are you open to moving styles to inline?  This makes it easier for consumers to install, without needing to also import another css file.

**Comment by mark-bradshaw** [comment]
Happy to help out, btw...

**Comment by terebentina** [comment]
I don't think inline styles are a very inspired choice in the js land currently. So I'm going to keep the styles in css for now. Either importing the styles in js or using `composes` from css modules should work just fine.
