### ISSUE TITLE
Style changes

### ISSUE THREAD

**Issue by mark-bradshaw** [terebentina/react-popover#8]
Consider changing the default background color to white, and text color to black.  I suspect this is the more normative case, and so will be less likely to need an override.

**Comment by terebentina** [comment]
I think this is highly subjective as it depends on the host site colors. I pretty much expect everyone would change the colors of the popover and possibly more than 1 variation/site.
But if you want you can send a PR with a `.theme--light` or something like this and I will be happy to include it in the main style.
