### ISSUE TITLE
Need to rebuild

### ISSUE THREAD

**Issue by mark-bradshaw** [terebentina/react-popover#9]
Looks like on the 1.2.0 version you forgot to rebuild before you published to npm.  Can you rebuild and publish?

**Comment by mark-bradshaw** [comment]
Any movement on this?

**Comment by terebentina** [comment]
Yeah, I'll try today when I finish work, including the other fix.

On 5/11/2016 3:44 PM, Mark Bradshaw wrote:

> Any movement on this?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/terebentina/react-popover/issues/9#issuecomment-218448031

## 

Cheers,
Dan
